"""initial_schema

Revision ID: d7ed7ff5e711
Revises: 
Create Date: 2025-11-04 02:02:43.208724

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd7ed7ff5e711'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jurisdiction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('esg_metadata', sa.JSON(), nullable=True),
    sa.Column('spatial_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_sources_category'), 'document_sources', ['category'], unique=False)
    op.create_index(op.f('ix_document_sources_jurisdiction'), 'document_sources', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_document_sources_region'), 'document_sources', ['region'], unique=False)
    op.create_index(op.f('ix_document_sources_status'), 'document_sources', ['status'], unique=False)
    op.create_index(op.f('ix_document_sources_title'), 'document_sources', ['title'], unique=False)
    op.create_index(op.f('ix_document_sources_topic'), 'document_sources', ['topic'], unique=False)
    op.create_table('monitoring_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('documents_checked', sa.Integer(), nullable=False),
    sa.Column('documents_discovered', sa.Integer(), nullable=False),
    sa.Column('documents_updated', sa.Integer(), nullable=False),
    sa.Column('documents_unchanged', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_logs_run_id'), 'monitoring_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_monitoring_logs_source_config_id'), 'monitoring_logs', ['source_config_id'], unique=False)
    op.create_index(op.f('ix_monitoring_logs_source_type'), 'monitoring_logs', ['source_type'], unique=False)
    op.create_index(op.f('ix_monitoring_logs_status'), 'monitoring_logs', ['status'], unique=False)
    op.create_table('query_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('query_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('topic_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jurisdiction_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_filters', sa.JSON(), nullable=True),
    sa.Column('source_documents', sa.JSON(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_history_created_at'), 'query_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_history_query_text'), 'query_history', ['query_text'], unique=False)
    op.create_index(op.f('ix_query_history_session_id'), 'query_history', ['session_id'], unique=False)
    op.create_table('document_files',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['document_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_files_content_hash'), 'document_files', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_files_filename'), 'document_files', ['filename'], unique=False)
    op.create_index(op.f('ix_document_files_source_id'), 'document_files', ['source_id'], unique=False)
    op.create_index(op.f('ix_document_files_status'), 'document_files', ['status'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('change_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('remote_last_modified', sa.DateTime(), nullable=True),
    sa.Column('remote_etag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['document_files.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['document_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_change_type'), 'document_versions', ['change_type'], unique=False)
    op.create_index(op.f('ix_document_versions_content_hash'), 'document_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_versions_file_id'), 'document_versions', ['file_id'], unique=False)
    op.create_index(op.f('ix_document_versions_is_current'), 'document_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_document_versions_source_id'), 'document_versions', ['source_id'], unique=False)
    op.create_index(op.f('ix_document_versions_status'), 'document_versions', ['status'], unique=False)
    op.create_index(op.f('ix_document_versions_version_number'), 'document_versions', ['version_number'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('page_range', sa.JSON(), nullable=True),
    sa.Column('section_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('section_hierarchy', sa.JSON(), nullable=True),
    sa.Column('clause_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_pdf_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deep_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('citation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_index', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['document_files.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['document_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_file_id'), 'document_chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_id'), 'document_chunks', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_source_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_file_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_document_versions_version_number'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_status'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_source_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_is_current'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_file_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_content_hash'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_change_type'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_files_status'), table_name='document_files')
    op.drop_index(op.f('ix_document_files_source_id'), table_name='document_files')
    op.drop_index(op.f('ix_document_files_filename'), table_name='document_files')
    op.drop_index(op.f('ix_document_files_content_hash'), table_name='document_files')
    op.drop_table('document_files')
    op.drop_index(op.f('ix_query_history_session_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_query_text'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_created_at'), table_name='query_history')
    op.drop_table('query_history')
    op.drop_index(op.f('ix_monitoring_logs_status'), table_name='monitoring_logs')
    op.drop_index(op.f('ix_monitoring_logs_source_type'), table_name='monitoring_logs')
    op.drop_index(op.f('ix_monitoring_logs_source_config_id'), table_name='monitoring_logs')
    op.drop_index(op.f('ix_monitoring_logs_run_id'), table_name='monitoring_logs')
    op.drop_table('monitoring_logs')
    op.drop_index(op.f('ix_document_sources_topic'), table_name='document_sources')
    op.drop_index(op.f('ix_document_sources_title'), table_name='document_sources')
    op.drop_index(op.f('ix_document_sources_status'), table_name='document_sources')
    op.drop_index(op.f('ix_document_sources_region'), table_name='document_sources')
    op.drop_index(op.f('ix_document_sources_jurisdiction'), table_name='document_sources')
    op.drop_index(op.f('ix_document_sources_category'), table_name='document_sources')
    op.drop_table('document_sources')
    # ### end Alembic commands ###
